spring.datasource.url=jdbc:postgresql://dpg-d7j07m9j2pic73b4m430-a.singapore-postgres.render.com:5432/attendance_db_794q
spring.datasource.username=auto
spring.datasource.password=r3WDm2tKzmbbp79SXqPnoXuU2Qconzt0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect